/**
 * This code was generated by BlueJinja
 *
 */

#ifndef __BLE_SERVICE_EXPOSE_DELEGATE_H__
#define __BLE_SERVICE_EXPOSE_DELEGATE_H__

class BLEServiceExposeDelegate {
public:
    virtual void onRecvEvent(std::string msg) = 0;
    virtual void onRecvISO(int iso) = 0;
    
}; // BLEServiceExposeDelegate

#endif __BLE_SERVICE_EXPOSE_DELEGATE_H__
